### ISSUE TITLE
Add a way to access and store addresses of deployed contracts.

### ISSUE THREAD

**Issue by Maxence-L** [eth-brownie/brownie#1003]
### Overview
Hi,

Chained deployment of contract, where you get the data from a previously deployed contract is different scripts, is currently difficult and error-prone. This is due to the fact that there is no (as far as I understand the docs) way to refer to 
 previously deployed instances (address + contract container) when executing multiple scripts separately.

The only way I found is to copy-paste the address in the scripts. Example :

We have two contracts : tokenContract and managingContract.

1_deploy_token.py
```python
from brownie import tokenContract

def main():
    acct = accounts.load('dev')
    tokenContract.deploy({from:acct})
````

As a result we get a console print of the deployment address.
```
Transaction sent: [transaction hash]
  Gas price: 10.0 gwei   Gas limit: 160000   Nonce: 5
  tokenContract.constructor confirmed - Block: 721000   Gas used: 1427907 (90.91%)
  tokenContract deployed at: "0xeD24FC36d5Ee211Ea25A80239Fb8C4Cfd80f12Ee"
```

The address is seemingly saved since running `tokenContract` in the console returns :
`[<tokenContract Contract '0xeD24FC36d5Ee211Ea25A80239Fb8C4Cfd80f12Ee'>]`

However the following code returns an error:
```python
print(tokenContract.address)

> File "<console>", line 1, in <module>
AttributeError: 'ContractContainer' object has no attribute 'address'
````

As a consequence, if we want to run a second script using the deployement address of the first, we need to paste it manually:

2_managing_contract.py
```python
from brownie import tokenContract, managingContract

def main():
    acct = accounts.load('dev')
    managing = managingContract.deploy({from:acct}), "0xeD24FC36d5Ee211Ea25A80239Fb8C4Cfd80f12Ee")
````

The need to copy-paste address is a source of error, especially in the following cases:
- Reuse of the script (what does the address belong to ?)
- Deployment of many contracts in the first script: the risk to paste the wrong address is high.

Besides, there is no easy way to find back the contracts implementation if the terminal/console is shut down. We need then to browse manually through the deployment folder's jsons - again, a source of potential errors.

### Specification

We need :
1. A getter function for the deployment address of a ContractContainer that is stored in the deployment map. This is the standard way shown in the doc and there's no way to get the address from the deployed ContractContainer object[1], which is quite confusing since it's the main info about the instance. Here's a simple implementation:
```python
from brownie import tokenContract

def main():
    acct = accounts.load('dev')
    tokenContract.deploy({from:acct})
    # Here's the getter function:
    print(tokenContract.address)

> "0xeD24FC36d5Ee211Ea25A80239Fb8C4Cfd80f12Ee"
````

Since the address is saved in the developement map, we should be able to do this too:
```python
# tokenContract has been deployed in another script run before this
from brownie import tokenContract

def main():
    print(tokenContract.address)

> "0xeD24FC36d5Ee211Ea25A80239Fb8C4Cfd80f12Ee"
`````

2. We may not want a mismatch between ContractContainer and the deployed ContractContainer.

As a result, we can add to it a method which allows to return an instanciated version of a deployed and saved ContractContainer (As you would get with accounts.load('dev').deploy(tokenContract)). This is how Truffle does it by the way:

```python
# tokenContract has been deployed in another script run before this
from brownie import tokenContract

# Here's the method
token = tokenContract.deployed()
print(token.address)

> "0xeD24FC36d5Ee211Ea25A80239Fb8C4Cfd80f12Ee"
```
3. A nice to have would be a global `clean` command-line function, removing every instance, just like `--reset` in Truffle.

[1]: Aside from copy-pasting and accessing `.address` attribute from a contract deployed with `account.load('id').deploy(TokenContract)` - which isn't persistent between sessions anyway.

**Comment by iamdefinitelyahuman** [comment]
The object you are using to deploy is called a [`ContractContainer`](https://eth-brownie.readthedocs.io/en/stable/api-network.html#brownie.network.contract.ContractContainer). The returned object is a [`ProjectContract`](https://eth-brownie.readthedocs.io/en/stable/api-network.html#brownie.network.contract.ProjectContract).  This returned object is also added within `ContractContainer`, which is a container that holds all the objects representing specific deployments of that contract.  For example:

```python
>>> type(MyContract)
<class 'brownie.network.contract.ContractContainer'>
>>> MyContract
[]  # currently empty

>>> deployment = MyContract.deploy({'from': accounts[0]})
Transaction sent: 0x98e9903d54aba84ec56178611043289e0b6d11877fec6da0e92cbf5a91a36748
  Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 0
  MyContract.constructor confirmed - Block: 1   Gas used: 438945 (3.66%)
  MyContract deployed at: 0xd495633B90a237de510B4375c442C0469D3C161C

>>> type(deployment)
<class 'brownie.network.contract.ProjectContract'>

>>> MyContract
[<MyContract Contract '0xd495633B90a237de510B4375c442C0469D3C161C'>]  # now contains 1 ProjectContract
>>> MyContract == deployment
False  # the container is not the deployment
>>> MyContract[0] == deployment
True  # the first object within the container IS the deployment
```


In a production environment, the `ProjectContract` objects within each `ContractContainer` object persist between sessions. So you can reference them between scripts by simply importing the container and pointing at index `-1` for the most recent deployment.

More generally, you can chain your deployment functions together within a single script so that you don't have issues with persistence when working in a local development environment:

```python
from brownie import tokenContract, managingContract

def deploy_token():
    acct = accounts.load('dev')
    return acct.deploy(tokenContract)

def deploy_manager():
    acct = accounts.load('dev')
    managing = acct.deploy(managingContract, tokenContract[-1])

def main():
    deploy_token()
    deploy_manager()
```

If this script is saved as `example.py`, we can run the `deploy_token` function via:

```
brownie run example deploy_token
```

If you want to remove a deployment artifact in a persistent environment, you can use e.g. `del MyContract[0]`. Or for a more nuclear option, delete the `build/` subdirectory within your project.

**Comment by Maxence-L** [comment]
Thanks a lot for your thorough and quick answer !

Maybe we should add this to the documentation, as it isn't mentioned as far as I know.

As a user feedback, multiple-scripts deployment allows to you run tests and checks between deployments. Aside from the users's peace of mind, it also saves Eth costs.

Anyway, thanks again, as a Python user Brownie is very comfy for me in this world of js code 😉

**Comment by iamdefinitelyahuman** [comment]
The relationship between `ProjectContract` and `ContractContainer` is fairly well documented under [Working with Contracts](https://eth-brownie.readthedocs.io/en/stable/core-contracts.html#deploying-contracts) and also touched on during the [Quickstart](https://eth-brownie.readthedocs.io/en/stable/quickstart.html#contracts). Given `ContractContainer` is effectively a list, I don't feel that a getter method would be more pythonic than simple index access.

I very much agree that splitting a deployment across multiple steps is good. But as per my previous example, you can accomplish this using a single script with multiple functions, and write it in a way that it can all execute in a single action within your test environment.

Also possibly relevant, you can use `-i` with `brownie run` to drop into a console after your test completes to verify the results immediately.  Or execute your scripts from within a console session using the [`run`](https://eth-brownie.readthedocs.io/en/stable/api-project.html#scripts.run) function, so that you can perform whatever checks are required between each step and the execute the next step within the same session.

**Comment by Maxence-L** [comment]
Thanks for your time and reply !

**Comment by RunyCalmera** [comment]
How can I get a contract that has already been deployed on a kovan nework back in my console after I closed the concole?

What is the code to get all the deployed contracts and the last deployed contract?
