### ISSUE TITLE
Compiling contract raises strange error from solc but solc does not complain when run directly

### ISSUE THREAD

**Issue by realisation** [eth-brownie/brownie#1147]
### Environment information

* `brownie` Version: 14.6.2
* `solc` Version: 0.8.2
* Python Version: ? just running brownie compile. python3 version is 3.8.5. python2 version is 2.7.16
* OS: osx

### What was wrong?

When I run brownie compile with this contract in my contracts folder

```
// SPDX-License-Identifier: Cheese
pragma solidity >=0.5.0;

contract UniswapV3OracleMock {
    constructor(
        uint256 _window,
        address _token0, 
        address _token1,
        int56[][] memory _observations
    ) { }
}
 ```

then brownie tells me that `CompilerError: Stack too deep when compiling inline assembly: Variable dataEnd is 1 slot(s) too deep inside the stack.`

But when I compile with the solc 0.8.2 binary directly, I don't get any such error.

**Comment by realisation** [comment]
removing 
`        uint256 _window,`
or
`        int56[][] memory _observations`
allows it to compile

**Comment by iamdefinitelyahuman** [comment]
This is likely related to optimizer settings within solidity.

**Comment by cameel** [comment]
This is indeed a problem in the compiler but not one that can be quickly "fixed". It stems from a limitation of the EVM (only 16 stack slots are reachable at any given time) and working around it requires significant changes in the compiler backend. Work on it is currently ongoing but for the time being you have to do manual workarounds if you encounter this. See for example this article for some suggestions: [Stack Too Deep. Three words of horror](https://soliditydeveloper.com/stacktoodeep).

Your particular situation seems similar to https://github.com/ethereum/solidity/issues/10930 so the workaround suggested there (disabling only the Yul optimizer with other optimizations still enabled) might be helpful too.

Overall this problem is not specific to Brownie so I'd suggest closing the issue and just waiting for this to be resolved in the compiler.
