### ISSUE TITLE
Error on trying to install latest Brownie version with pipx

### ISSUE THREAD

**Issue by AoDev** [eth-brownie/brownie#1638]
### Environment information

* `brownie` latest
* Python Version: Python 3.8.9
* OS: osx

Got this error when running `pipx install eth-brownie`

```
pip failed to build packages:
    lru-dict
    psutil

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    lru.c:1:10: fatal error: 'Python.h' file not found
    error: command '/usr/bin/clang' failed with exit code 1
    psutil/_psutil_common.c:9:10: fatal error: 'Python.h' file not found
```

**Comment by mattjaf** [comment]
what version of ganache are you using?

**Comment by tokigith** [comment]
@mattjaf The TLDR is I downgraded the python version to make it work.

Here are the details.

You need to use `pyenv` to install python **3.8** instead of using the python version that comes with MacOS or homebrew. For multiple users on the same machine, using pyenv also helps.

## Pre-check
If you tried to install brownie through other methods, try to cleanup first (brew, pipx).

## Install pyenv
* install pyenv [GitHub - pyenv/pyenv: Simple Python version management](https://github.com/pyenv/pyenv)
	* `curl https://pyenv.run | bash` (NOT homebrew)
	* in zshrc add
	
```
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
```

*Check*
```
> which pyenv
 > echo $PATH | grep --color=auto "$(pyenv root)/shims"
```

## Install python with pyenv
* `pyenv install 3.8.14`
* `pyenv global 3.8.14`
* `brew install openssl readline sqlite3 xz zlib tcl-tk` 
(was told after installation, depends on your setup [Home · pyenv/pyenv Wiki · GitHub](https://github.com/pyenv/pyenv/wiki#suggested-build-environment))

## Install brownie
* `pip install eth-brownie` (no pipx)

## Resources
[Homebrew Python Is Not For You // Justin Mayer](https://justinmayer.com/posts/homebrew-python-is-not-for-you/)

## Others
Uninstall pipx:  `pip uninstall pipx`

**Comment by AoDev** [comment]
@mattjaf The TLDR is I downgraded the python version to make it work.

Here are the details.

You need to use `pyenv` to install python **3.8** instead of using the python version that comes with MacOS or homebrew. For multiple users on the same machine, using pyenv also helps.

## Pre-check
If you tried to install brownie through other methods, try to cleanup first (brew, pipx).

## Install pyenv
* install pyenv [GitHub - pyenv/pyenv: Simple Python version management](https://github.com/pyenv/pyenv)
	* `curl https://pyenv.run | bash` (NOT homebrew)
	* in zshrc add
	
```
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
```

*Check*
```
> which pyenv
 > echo $PATH | grep --color=auto "$(pyenv root)/shims"
```

## Install python with pyenv
* `pyenv install 3.8.14`
* `pyenv global 3.8.14`
* `brew install openssl readline sqlite3 xz zlib tcl-tk` 
(was told after installation, depends on your setup [Home · pyenv/pyenv Wiki · GitHub](https://github.com/pyenv/pyenv/wiki#suggested-build-environment))

## Install brownie
* `pip install eth-brownie` (no pipx)

## Resources
[Homebrew Python Is Not For You // Justin Mayer](https://justinmayer.com/posts/homebrew-python-is-not-for-you/)

## Others
Uninstall pipx:  `pip uninstall pipx`

**Comment by mattjaf** [comment]
Why not pipx? I did something very similar on windows.

If ur pipx was still erroring it might be due to an old folder that was created somewhere when you ran ensurepath with the previous python installation

**Comment by AoDev** [comment]
I suppose it could work. I had troubles with homebrew, python, pipx,...

I am not a python dev, so it just seemed that pipx added more oil to the fire. I installed it with `brew` originally but brew can cause troubles with multiple users. I suppose if I had installed it with pip instead of brew, it would have worked. 

So, everything that I did above allowed me to:
- have a version of python that Brownie supports
- easily change version of python is needed
- have a user independent setup
