### ISSUE TITLE
Pass more flags to pytest

### ISSUE THREAD

**Issue by WyseNynja** [eth-brownie/brownie#560]
### Overview

I have some tests marked xfail and I noticed that they started passing.

I tried to get more info about these like the [pytest docs](https://docs.pytest.org/en/latest/skipping.html) say to, but brownie doesn't pass these flags through.

### Specification

Rather than add a bunch of flags to brownie, I think there could be a "--" flag and everything after that just gets passed to pytest.

```
brownie test --  -rxXs
```

**Comment by iamdefinitelyahuman** [comment]
A big part of the reason Brownie offers a limited subset of `pytest` flags is because of the amount of voodoo happening to allow things like with isolation and coverage.  The test surface is exponentially larger when you add in all the extra flags, almost definitely something will end up breaking.  Forcing the user to type `python -m pytest` in my mind is akin to an acknowledgement of "I'm doing something that might not be supported".

That said, I'm not inherently opposed to this change. Perhaps raising a warning with it's use that "here be (maybe) dragons" - this would be even more explicit than the current approach.

**Comment by iamdefinitelyahuman** [comment]
Related - it should be possible to pass multiple test filenames.
