### ISSUE TITLE
"macOS 11 or later required" on MacOS 11 (M1 processor)

### ISSUE THREAD

**Issue by DanielVF** [eth-brownie/brownie#912]
### Environment information

* `brownie` Version: 1.12.3
* `ganache-cli` : n/a
* `solc` Version: n/a
* Python Version: 3.9.1
* OS: 11.1 Big Sur
* CPU: Apple M1 Processor

### What was wrong?

```
$ brownie gui
Brownie v1.12.3 - Python development framework for Ethereum

Loading Brownie GUI...
macOS 11 or later required !
fish: 'brownie gui' terminated by signal SIGABRT (Abort)
```

**Comment by iamdefinitelyahuman** [comment]
Seems there is an in the way `brew` installs Python in Big Sur ([source](https://bugs.python.org/issue42480)).  I don't have a Mac so I can't verify, but this [Stack Overflow thread](https://stackoverflow.com/questions/65315077/interpreter-crashes-trying-to-use-tkinter-library) suggests installing Python through the [official site](https://www.python.org/downloads/mac-osx/) instead of using `brew`.

**Comment by DanielVF** [comment]
Thanks. Best of luck with Brownie!
