### ISSUE TITLE
Don't download solc

### ISSUE THREAD

**Issue by hacker-DOM** [eth-brownie/brownie#949]
It would be great if it was possible to prevent `brownie` from downloading solc. I am using [solc-select](https://github.com/crytic/solc-select), and I suspect brownie doesn't like that and redownloads solc, even though all my contracts have `pragma solidity 0.7.3` and `solc --version` gives 0.7.3. Hope that helps!

**Comment by iamdefinitelyahuman** [comment]
Brownie is using [`py-solc-x`](https://github.com/iamdefinitelyahuman/py-solc-x) under the hood to deal with Solidity version management. Normally `py-solc-x` will detect an installed verion of `solc` and use it rather than downloading, but I guess it's incompatible with `solc-select`.  Probably it would be possible to make them play nicely together.

**Comment by iamdefinitelyahuman** [comment]
I've opened a related issue on `py-solc-x`: https://github.com/iamdefinitelyahuman/py-solc-x/issues/122

Closing this for now.
