### ISSUE TITLE
pip package has fixed requirement versions

### ISSUE THREAD

**Issue by spapinistarkware** [eth-brownie/brownie#991]
This is an antipattern, and makes it very hard to install in an existing virtual environment (for example, it clashes with web3==5.16.0)
The pip package requirements should contain loosened requirements for dependency packages.
For example, instead of eth-account==0.5.2, have eth-account>=0.5.2,<0.6, for example

**Comment by iamdefinitelyahuman** [comment]
Strict pins are to avoid breaking changes within dependencies that sometimes occur on minor or patch releases.  For example, brownie works fine with web3 `5.11.0` but aspects will break using `5.16.0`.  `eth-account` is a similar situation, going beyond the currently pinned patch version will break some functionality.  At one point the `semantic-version` library broke brownie with a breaking change in it's `2.8.1` release. There is some irony in that a library focused on semantic versioning doesn't adhere to semver :)

Point being, with floating pins it's possible that a version of brownie that works on the date of it's release will stop working at some point in the future due to a breaking change within a dependency. This leads to projects that rely on brownie having sudden CI failures when nothing has changed, and then a sudden urgency to solve the dependency-created problem and push a new patch release.

For this reason I respectfully disagree with you that this an antipattern. The best solution in my mind is to install brownie in it's own virtual environment - `venv` exists precisely to isolate installations so we can avoid dependency conflicts. If you have a hard requirement for brownie to work with a newer version of `web3` I'm open to a pull request. I unfortunately haven't yet found the bandwidth to take care of this myself.

**Comment by spapinistarkware** [comment]
I had a feeling you were going to say that. I did not say put unbound requirements. From your example, it seems >=5.11,<=5.15 is a valid range, so why restrict further?
When you restrict it, another projects called eth-brownie2, uses 5.12.0, and I can't have both.

When you use brownie as an independent command line tool, your approach works. But when I use it as a library, where I import things, it imposes problems.

**Comment by WyseNynja** [comment]
Even bounded requirements have been a big headache. Upstream deps have been rather bad about sticking to proper semver. Even the semver package had a breaking patch version.

Given that brownie is primarily a command line tool, I think we need to keep hard pins as the default. However, I definitely see the argument when using brownie as a library. This is more python's fault for not handling packages that can be a library and a package well.

I think #993 might keep everyone happy:

1. Normal users doing `pip install eth-brownie` will get hard pins from .txt that won't surprise anyone.
2. People using brownie as a library do `export BROWNIE_LIB=1` and then they can have soft pins.
3. When brownie is going to release, the dev does `pip-compile --upgrade` and tests things. if something is broken, they can tweak the soft pins and re-run pip-compile.

**Comment by spapinistarkware** [comment]
That sounds great, thank you.
