### ISSUE TITLE
Allow testing from another working directory

### ISSUE THREAD

**Issue by spapinistarkware** [eth-brownie/brownie#994]
I want to use brownie pytest plugin, but our testing framework runs pytest from another working directory.
Currently, the pytest plugin uses check_for_project('.').

A possible solution is to add an environment variable with the real path of the project, and make check_for_project() search there as well.

**Comment by spapinistarkware** [comment]
When I added this change manually, along with O(1) other fixes, it works great.
One of the changes I had to do though is at test/managers/base.py,

def _path(self, path):
        return self.project_path.joinpath(path).relative_to(self.project_path).as_posix()
=>
def _path(self, path):
        return path

I was wondering why you have this logic there? Why are you not using absolute paths?

**Comment by iamdefinitelyahuman** [comment]
Generally, brownie is using relative paths everywhere so that data in the `build` folder isn't invalidated when a project is moved to a different folder or system.  In this specific case the paths are being used to track coverage data and to decide when a test needs to be rerun if using the `-U` flag.

I guess the issue you're hitting here is that you are collecting tests outside of a project?  Could probably add logic to detect this situation, and thus fall back to an absolute path.  It might mean you can't use `-U` correctly but that's better than not being able to use it at all.

**Comment by iamdefinitelyahuman** [comment]
As for the initial issue, would a commandline flag `--brownie-project path/to/project` work?

**Comment by spapinistarkware** [comment]
You are correct, my tests are outside the project.
If you make the flag work, I will be delighted, but I think it will cause issues with your pytest_addoption(), since you will need to add the brownie-project flag there, but this place already needs to know what is the project dir there, since you decide if you want to add the other flags.

But if you make it work, then yes, it will help
